services:
  - type: web
    name: dieppe-vlog
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php -S 0.0.0.0:$PORT -t public/
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: dieppe-vlog-db
          property: connectionString

databases:
  - name: dieppe-vlog-db
    plan: free
    ipAllowList: []

disks:
  - name: uploads
    mountPath: /var/www/html/public/uploads
    sizeGB: 1 